- name: add Golang PPA
  apt_repository: repo='ppa:gophers/archive'

- name: install golang
  apt: name=golang-1.9-go

- name: get wal-g sources
  shell: GOPATH=/root/wal-g-gopath /usr/lib/go-1.9/bin/go get github.com/wal-g/wal-g

- name: compile wal-g
  shell: cd /root/wal-g-gopath/src/github.com/wal-g/wal-g && PATH=/usr/lib/go-1.9/bin:$PATH GOPATH=/root/wal-g-gopath make all

- name: install wal-g
  shell: cd /root/wal-g-gopath/src/github.com/wal-g/wal-g && PATH=/usr/lib/go-1.9/bin:$PATH GOPATH=/root/wal-g-gopath GOBIN=/usr/local/bin make install
